language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy"
    - "pypy3"
script:
    - pip install -r test-requirements.txt
    - python setup.py install
    - cd tests && py.test
